package jku.se.controller;

import java.io.IOException;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.stage.Stage;
import javafx.scene.layout.Pane;
import javafx.scene.Node;
import javafx.event.ActionEvent;

import static jku.se.Login.logout;

public abstract class Controller {
    protected void switchScene(ActionEvent event, String fxmlFile) throws IOException {
        FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("/" + fxmlFile));
        Pane pane = fxmlLoader.load();
        Stage stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
        Scene scene = new Scene(pane);
        stage.setScene(scene);
        stage.show();
    }

    @FXML
    private void handleLogout(ActionEvent event) throws IOException {
        logout();
        switchScene(event, "login.fxml");
    }

    // generated by AI
    public static void showError(String title, String message) {// Fehlermeldungen
        Alert alert = new Alert(Alert.AlertType.ERROR);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }

    // generated by AI
    public static void showInfo(String title, String message) { // Infomeldung
        Alert alert = new Alert(Alert.AlertType.INFORMATION);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }

    // generated by AI
    public static void showSuccess(String title, String message) { // Erfolgsmeldung
        Alert alert = new Alert(Alert.AlertType.INFORMATION);
        alert.setTitle(title);
        alert.setHeaderText("Success");
        ImageView successIcon = new ImageView(new Image("file:src/test/resources/check_mark.png"));

        successIcon.setFitWidth(20);
        successIcon.setFitHeight(20);
        alert.setGraphic(successIcon);
        alert.setContentText(message);
        alert.showAndWait();
    }
}
