package jku.se.Controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.control.*;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import jku.se.InvoiceStatus;
import jku.se.InvoiceType;

import java.io.IOException;
import java.sql.Date;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Optional;

import static jku.se.Database.*;

public class EditInvoiceUserController extends Controller{
    @FXML
    public Label labelRechnungsID;
    @FXML
    public ComboBox comboBoxTyp;
    @FXML
    public TextField textfieldUsername;
    @FXML
    public ComboBox comboBoxStatus;
    @FXML
    public TextField textfieldImage;
    @FXML
    public TextField textfieldRefund;
    @FXML
    public TextField textFieldBetrag;
    @FXML
    public TextField textfieldDatum;

    private int invoiceId;
    private double amount;
    private String date;
    private String typ;
    private String user;

    @FXML
    public void initialize() {
        comboBoxTyp.getItems().addAll(
                InvoiceType.SUPERMARKET.name(),
                InvoiceType.RESTAURANT.name()
        );

    }

    @FXML
    public void saveChangesUser() throws IOException {
        // Hole die bearbeiteten Werte aus den Textfeldern und speichere sie in der Datenbank
        int id = Integer.parseInt(labelRechnungsID.getText());
        double betrag = Double.parseDouble(textFieldBetrag.getText());
        Date datum = null;


        try {
            datum = Date.valueOf(textfieldDatum.getText());
        } catch (IllegalArgumentException e) {
            showAlert("Error", "Please enter a valid date in the format yyyy-mm-dd.");
            return; // Update wird abgebrochen, falls das Datum ungültig ist
        }

        String typString = (String) comboBoxTyp.getValue();

        if (betrag < 0) {
            // negativer Rechnungsbetrag
            showAlert("Error", "Negative Beträge sind nicht erlaubt!");
            return; // Update wird abgebrochen
        }

        InvoiceType typ = InvoiceType.valueOf((String) comboBoxTyp.getValue());
        String username = getInvoiceUsername(id);
        InvoiceStatus status = InvoiceStatus.valueOf(getInvoiceStatus(id));
        String image = getInvoiceImage(id);
        double refund = getInvoiceRefund(id);

        boolean success = updateInvoice(betrag, datum, typ, username, status, image, refund, id);
        if (success) {
            showAlertSuccess("Erfolg", "Rechnung wurde erfolgreich aktualisiert.");
        } else {
            showAlert("Fehler", "Rechnung konnte nicht aktualisiert werden.");
        }
    }

    // Methode zum Anzeigen von Fehlerbenachrichtigungen (Alert)
    public void showAlert(String title, String message) { //generated by AI
        Alert alert = new Alert(Alert.AlertType.ERROR);  // oder AlertType.INFORMATION je nach Bedarf
        alert.setTitle(title);
        alert.setHeaderText("Error");  // Optional: Header Text entfernen
        alert.setContentText(message);
        alert.showAndWait();
    }

    public void showAlertSuccess(String title, String message) { //generated by AI
        Alert alert = new Alert(Alert.AlertType.INFORMATION);  // oder AlertType.INFORMATION je nach Bedarf
        alert.setTitle(title);
        alert.setHeaderText("Success");
        ImageView successIcon = new ImageView(new Image("file:src/test/resources/check_mark.png"));

        successIcon.setFitWidth(20);
        successIcon.setFitHeight(20);
        alert.setGraphic(successIcon);  // Dein grünes Häkchen-Icon hier
        alert.setContentText(message);
        alert.showAndWait();
    }

    public void setInvoice(int id, double amount, String typ, String date, String user) { //Wird für Ausfüllung von fxml Spalten benötigt
        this.invoiceId = id;
        this.amount = amount;
        this.typ = typ;
        this.date = date;
        this.user = user; //wird nur benötigt falls die datei gelöscht wird
        labelRechnungsID.setText(String.valueOf(id));
        textFieldBetrag.setText(String.valueOf(amount));
        comboBoxTyp.setValue(String.valueOf(typ));
        textfieldDatum.setText(String.valueOf(date));
    }

    @FXML
    private void goBackToInvoicesUser(javafx.event.ActionEvent event) throws IOException{
        switchScene(event, "submittedBills.fxml");

    }

    @FXML
    private void handleDeleteInvoiceUser() throws SQLException {
        Alert alert = new Alert(Alert.AlertType.CONFIRMATION);
        alert.setTitle("Delete Confirmation");
        alert.setHeaderText(null);
        alert.setContentText("Are you sure you want to delete this invoice?");

        Optional<ButtonType> result = alert.showAndWait();
        if (result.isPresent() && result.get() == ButtonType.OK) {
            deleteInvoice(getConnection(), user, LocalDate.parse(date));//globale user variable, weil kann bei User nicht aus Textfield hergenommen werden
        }
    }

    public static EditInvoiceController loadEditInvoiceController() throws IOException {
        FXMLLoader loader = new FXMLLoader(EditInvoiceController.class.getResource("/editInvoice.fxml"));
        Parent root = loader.load();  // Läd die FXML-Datei
        return loader.getController();  // Gibt den Controller zurück
    }

}
