# Root logger auf INFO setzen und Konsole als Ziel
log4j.rootLogger=INFO, stdout

# Konsole-Appender konfigurieren
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{HH:mm:ss} %-5p %c{1} - %m%n
